apiVersion: v1
kind: Service
metadata:
  name: ms-car-ops-producer
spec:
  type: LoadBalancer
  selector:
    app: ms-car-ops-producer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
